ERROR:root:Exception occurred
Traceback (most recent call last):
  File "/home/yevhen/Cursor/Practice/Git/firstproj-git/context_manager_wwf/context.py", line 36, in <module>
    b = c
NameError: name 'c' is not defined
INFO:root:

ERROR:root:Exception occurred
Traceback (most recent call last):
  File "/home/yevhen/Cursor/Practice/Git/firstproj-git/context_manager_wwf/context.py", line 38, in <module>
    c = a / b
ZeroDivisionError: division by zero
INFO:root:

ERROR:root:Exception occurred
Traceback (most recent call last):
  File "/home/yevhen/Cursor/Practice/Git/firstproj-git/context_manager_wwf/context.py", line 37, in <module>
    with open('nonexistent_file.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'nonexistent_file.txt'
INFO:root:

ERROR:root:Exception occurred
Traceback (most recent call last):
  File "/home/yevhen/Cursor/Practice/Git/firstproj-git/context_manager_wwf/context.py", line 42, in <module>
    c = a / b
TypeError: unsupported operand type(s) for /: 'str' and 'int'
INFO:root:

ERROR:root:Exception occurred
Traceback (most recent call last):
  File "/home/yevhen/Cursor/Practice/Git/firstproj-git/context_manager_wwf/context.py", line 36, in <module>
    b = c
NameError: name 'c' is not defined
INFO:root:

